services:
  accounts:
    image: "tilak0110/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - tilaknetwork
  loans:
    image: "tilak0110/loans:s4"
    container_name: loans-ms
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - tilaknetwork
  cards:
    image: "tilak0110/cards:s4"
    container_name: cards-ms
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - tilaknetwork
networks:
  tilaknetwork:
    driver: "bridge"