server:
  port: 8084

spring:
  application:
    name : order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
#  cloud:
#    loadbalancer:
#      instances:
#        inventory-service:
#          - uri: http://localhost:8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost

logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.web.reactive: DEBUG

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
    metrics:
      tags:
        application: ${spring.application.name}
