console.log("5" + 1);   // "51" (string)
console.log("5" - 1);   // 4   (number)
console.log(true + 1);  // 2   (true becomes 1)
console.log(false + 1); // 1   (false becomes 0)
console.log("5" * 2);   // 10  (string coerced to number)
console.log("5" / 2);   // 2.5 (string coerced to number)
console.log("5" == 5);  // true (string coerced to number for comparison)
console.log("5" === 5); // false (strict equality, no coercion)     
console.log(null == undefined); // true (loose equality, both are coerced to false)
console.log(null === undefined); // false (strict equality, no coercion)
console.log("5" + true); // "5true" (string concatenation)
console.log("5" - true); // 4 (true coerced to 1, string coerced to number)
console.log("5" * false); // 0 (false coerced to 0, string coerced to number)
console.log("5" / false); // Infinity (false coerced to 0, division by zero)
console.log("5" + null); // "5null" (string concatenation)  
