server:
  port: 8084
  ssl:
    enabled: false

spring:
  application:
    name: orchestrator-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.example.common_events.dto,com.fasterxml.jackson.databind.node"
        spring.json.value.default.type: com.example.common_events.dto.BaseEvent
        spring.json.type.mapping: |
          OrderEvent:com.example.common_events.dto.OrderEvent,
          InventoryEvent:com.example.common_events.dto.InventoryEvent,
          PaymentEvent:com.example.common_events.dto.PaymentEvent
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: |
          OrderEvent:com.example.common_events.dto.OrderEvent,
          InventoryEvent:com.example.common_events.dto.InventoryEvent,
          PaymentEvent:com.example.common_events.dto.PaymentEvent

