
server:
  port: 8888
spring:
  application:
    name: "configserver"
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/tilak0110/config-repo.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true