
spring:
  application:
    name: "configserver"
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
#          search-locations: 'file:C:\Users\tilak\OneDrive\Desktop\Learnings\ASPL-internship-training\Microservices\udemycourse\Configuration SetUp\V2-spring-cloud-config\configserver\src\main\resources\config'
        git:
          uri: "https://github.com/tilak0110/spring-cloud-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

server:
  port: 8071