-- DECIMAL and NUMERIC
SELECT CAST(123 AS DECIMAL(5,2)); 
SELECT CAST(12345.12 AS NUMERIC(10,5)); 

-- FLOAT and REAL
SELECT CAST(PI() AS FLOAT); 
SELECT CAST(PI() AS REAL);

-- Integers
SELECT CAST(100 AS BIGINT);
SELECT CAST(100 AS INT);
SELECT CAST(100 AS SMALLINT);
SELECT CAST(100 AS TINYINT);

-- MONEY and SMALLMONEY
SELECT CAST(123456.78 AS MONEY);
SELECT CAST(1234.56 AS SMALLMONEY);

-- BINARY and VARBINARY
SELECT CAST(12345 AS BINARY(10)); 
SELECT CAST(12345 AS VARBINARY(10));
-- CHAR and VARCHAR
SELECT CAST('ABC' AS CHAR(10)); -- 'ABC       '
SELECT CAST('ABC' AS VARCHAR(10)); -- 'ABC'
SELECT CAST('ABCDEFGHIJKLMNOPQRSTUVWXYZ' AS CHAR(10));  -- 'ABCDEFGHIJ'

-- NCHAR and NVARCHAR
SELECT CAST('Hello' AS NCHAR(10));
SELECT CAST('Hello' AS NVARCHAR(10));

-- UNIQUEIDENTIFIER
DECLARE @GUID UNIQUEIDENTIFIER = NEWID();
SELECT @GUID;
